"use client"

import { useState, useMemo } from "react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

interface TaxSummary {
  year: number
  totalIncome: number
  totalExpenses: number
  netIncome: number
  estimatedTax: number
  quarterlyPayments: number[]
  brands: { name: string; amount: number }[]
  expensesByCategory: { category: string; amount: number }[]
}

const allTaxData: Record<number, TaxSummary> = {
  2026: {
    year: 2026,
    totalIncome: 85000,
    totalExpenses: 12500,
    netIncome: 72500,
    estimatedTax: 18125,
    quarterlyPayments: [4531, 4531, 4531, 4532],
    brands: [
      { name: "Nike", amount: 25000 },
      { name: "Gymshark", amount: 18000 },
      { name: "Samsung", amount: 15000 },
      { name: "Audible", amount: 12000 },
      { name: "Adobe", amount: 8000 },
      { name: "Other", amount: 7000 },
    ],
    expensesByCategory: [
      { category: "Equipment", amount: 4500 },
      { category: "Software", amount: 2400 },
      { category: "Travel", amount: 2000 },
      { category: "Studio", amount: 1800 },
      { category: "Props", amount: 1200 },
      { category: "Other", amount: 600 },
    ],
  },
  2025: {
    year: 2025,
    totalIncome: 62000,
    totalExpenses: 9800,
    netIncome: 52200,
    estimatedTax: 13050,
    quarterlyPayments: [3262, 3262, 3263, 3263],
    brands: [
      { name: "Nike", amount: 18000 },
      { name: "Audible", amount: 15000 },
      { name: "Samsung", amount: 12000 },
      { name: "Adobe", amount: 10000 },
      { name: "Other", amount: 7000 },
    ],
    expensesByCategory: [
      { category: "Equipment", amount: 3500 },
      { category: "Software", amount: 2000 },
      { category: "Travel", amount: 1800 },
      { category: "Studio", amount: 1500 },
      { category: "Props", amount: 600 },
      { category: "Other", amount: 400 },
    ],
  },
  2024: {
    year: 2024,
    totalIncome: 45000,
    totalExpenses: 7200,
    netIncome: 37800,
    estimatedTax: 9450,
    quarterlyPayments: [2362, 2362, 2363, 2363],
    brands: [
      { name: "Nike", amount: 12000 },
      { name: "Audible", amount: 10000 },
      { name: "Adobe", amount: 8000 },
      { name: "Spotify", amount: 8000 },
      { name: "Other", amount: 7000 },
    ],
    expensesByCategory: [
      { category: "Equipment", amount: 2500 },
      { category: "Software", amount: 1800 },
      { category: "Travel", amount: 1200 },
      { category: "Studio", amount: 1000 },
      { category: "Props", amount: 400 },
      { category: "Other", amount: 300 },
    ],
  },
}

export default function TaxPage() {
  const [selectedYear, setSelectedYear] = useState(2026)

  const taxRate = 0.25
  const selfEmploymentTax = 0.153

  const taxData = useMemo(() => allTaxData[selectedYear], [selectedYear])

  const previousYears = useMemo(() => {
    return Object.values(allTaxData)
      .filter(d => d.year !== selectedYear)
      .sort((a, b) => b.year - a.year)
      .map(d => ({
        year: d.year,
        income: d.totalIncome,
        expenses: d.totalExpenses,
        tax: d.estimatedTax,
      }))
  }, [selectedYear])

  const handleExport = () => {
    const report = `
TAX REPORT ${selectedYear}
========================

INCOME SUMMARY
Total Income: $${taxData.totalIncome.toLocaleString()}
Total Expenses: $${taxData.totalExpenses.toLocaleString()}
Net Income: $${taxData.netIncome.toLocaleString()}
Estimated Tax: $${taxData.estimatedTax.toLocaleString()}

INCOME BY BRAND
${taxData.brands.map(b => `- ${b.name}: $${b.amount.toLocaleString()}`).join('\n')}

EXPENSES BY CATEGORY
${taxData.expensesByCategory.map(c => `- ${c.category}: $${c.amount.toLocaleString()}`).join('\n')}

QUARTERLY PAYMENTS
Q1 (Apr 15): $${taxData.quarterlyPayments[0].toLocaleString()}
Q2 (Jun 15): $${taxData.quarterlyPayments[1].toLocaleString()}
Q3 (Sep 15): $${taxData.quarterlyPayments[2].toLocaleString()}
Q4 (Jan 15): $${taxData.quarterlyPayments[3].toLocaleString()}

Generated by ContractGen
    `.trim()

    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `tax-report-${selectedYear}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="p-6 lg:p-8 max-w-6xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold tracking-tight mb-2">Tax Reports</h1>
          <p className="text-zinc-500">Track income, expenses, and estimated taxes</p>
        </div>
        <div className="flex gap-2">
          <select
            value={selectedYear}
            onChange={(e) => setSelectedYear(parseInt(e.target.value))}
            className="h-10 px-4 bg-white/5 border border-white/10 rounded-xl text-white"
          >
            <option value={2026}>2026</option>
            <option value={2025}>2025</option>
            <option value={2024}>2024</option>
          </select>
          <Button
            onClick={handleExport}
            className="bg-gradient-to-r from-violet-600 to-fuchsia-600 hover:from-violet-500 hover:to-fuchsia-500"
          >
            <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Export Report
          </Button>
        </div>
      </div>

      {/* Main Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <Card className="bg-white/[0.02] border-white/5 rounded-xl">
          <CardContent className="p-5">
            <div className="text-sm text-zinc-500">Total Income</div>
            <div className="text-3xl font-bold text-emerald-400">${taxData.totalIncome.toLocaleString()}</div>
          </CardContent>
        </Card>
        <Card className="bg-white/[0.02] border-white/5 rounded-xl">
          <CardContent className="p-5">
            <div className="text-sm text-zinc-500">Total Expenses</div>
            <div className="text-3xl font-bold text-red-400">${taxData.totalExpenses.toLocaleString()}</div>
          </CardContent>
        </Card>
        <Card className="bg-white/[0.02] border-white/5 rounded-xl">
          <CardContent className="p-5">
            <div className="text-sm text-zinc-500">Net Income</div>
            <div className="text-3xl font-bold">${taxData.netIncome.toLocaleString()}</div>
          </CardContent>
        </Card>
        <Card className="bg-white/[0.02] border-white/5 rounded-xl">
          <CardContent className="p-5">
            <div className="text-sm text-zinc-500">Est. Tax Owed</div>
            <div className="text-3xl font-bold text-amber-400">${taxData.estimatedTax.toLocaleString()}</div>
          </CardContent>
        </Card>
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        {/* Income Breakdown */}
        <div className="lg:col-span-2 space-y-6">
          <Card className="bg-white/[0.02] border-white/5 rounded-xl">
            <CardContent className="p-6">
              <h2 className="font-semibold mb-4">Income by Brand ({selectedYear})</h2>
              <div className="space-y-3">
                {taxData.brands.map((brand, i) => (
                  <div key={i} className="flex items-center gap-4">
                    <div className="flex-1">
                      <div className="flex justify-between text-sm mb-1">
                        <span>{brand.name}</span>
                        <span className="font-medium">${brand.amount.toLocaleString()}</span>
                      </div>
                      <div className="h-2 bg-white/5 rounded-full overflow-hidden">
                        <div
                          className="h-full bg-gradient-to-r from-violet-500 to-fuchsia-500 rounded-full"
                          style={{ width: `${(brand.amount / taxData.totalIncome) * 100}%` }}
                        />
                      </div>
                    </div>
                    <span className="text-xs text-zinc-500 w-12 text-right">
                      {Math.round((brand.amount / taxData.totalIncome) * 100)}%
                    </span>
                  </div>
                ))}
              </div>

              {/* 1099 Alert */}
              <div className="mt-6 p-4 bg-amber-500/10 border border-amber-500/20 rounded-xl">
                <div className="flex items-start gap-3">
                  <span className="text-xl">⚠️</span>
                  <div>
                    <div className="font-medium text-amber-400 mb-1">1099 Forms Expected</div>
                    <div className="text-sm text-zinc-400">
                      You should receive 1099-NEC forms from {taxData.brands.filter(b => b.amount >= 600).length} brands
                      who paid you $600+. Make sure to report all income even without a 1099.
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Expenses Breakdown */}
          <Card className="bg-white/[0.02] border-white/5 rounded-xl">
            <CardContent className="p-6">
              <h2 className="font-semibold mb-4">Deductible Expenses ({selectedYear})</h2>
              <div className="grid grid-cols-2 gap-4">
                {taxData.expensesByCategory.map((cat, i) => (
                  <div key={i} className="p-4 bg-white/5 rounded-xl">
                    <div className="text-2xl font-bold">${cat.amount.toLocaleString()}</div>
                    <div className="text-sm text-zinc-500">{cat.category}</div>
                  </div>
                ))}
              </div>

              <div className="mt-4 p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-xl">
                <div className="flex items-center gap-2">
                  <span className="text-xl">💰</span>
                  <div>
                    <span className="text-emerald-400 font-medium">Tax Savings: </span>
                    <span className="text-zinc-300">
                      ${Math.round(taxData.totalExpenses * taxRate).toLocaleString()} saved by deducting expenses
                    </span>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Right Column */}
        <div className="space-y-6">
          {/* Quarterly Payments */}
          <Card className="bg-white/[0.02] border-white/5 rounded-xl">
            <CardContent className="p-6">
              <h2 className="font-semibold mb-4">Quarterly Payments ({selectedYear})</h2>
              <div className="space-y-3">
                {["Q1 (Apr 15)", "Q2 (Jun 15)", "Q3 (Sep 15)", "Q4 (Jan 15)"].map((quarter, i) => (
                  <div key={i} className="flex items-center justify-between p-3 bg-white/5 rounded-xl">
                    <span className="text-sm">{quarter}</span>
                    <span className="font-semibold">${taxData.quarterlyPayments[i].toLocaleString()}</span>
                  </div>
                ))}
              </div>
              <div className="mt-4 text-xs text-zinc-500">
                * Based on 25% income tax + 15.3% self-employment tax
              </div>
            </CardContent>
          </Card>

          {/* Tax Summary */}
          <Card className="bg-white/[0.02] border-white/5 rounded-xl">
            <CardContent className="p-6">
              <h2 className="font-semibold mb-4">Tax Breakdown ({selectedYear})</h2>
              <div className="space-y-3">
                <div className="flex justify-between text-sm">
                  <span className="text-zinc-400">Gross Income</span>
                  <span>${taxData.totalIncome.toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-zinc-400">- Deductions</span>
                  <span className="text-red-400">-${taxData.totalExpenses.toLocaleString()}</span>
                </div>
                <div className="border-t border-white/5 pt-3 flex justify-between text-sm">
                  <span className="text-zinc-400">Net Income</span>
                  <span className="font-medium">${taxData.netIncome.toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-zinc-400">Income Tax (25%)</span>
                  <span>${Math.round(taxData.netIncome * taxRate).toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-zinc-400">Self-Employment (15.3%)</span>
                  <span>${Math.round(taxData.netIncome * selfEmploymentTax).toLocaleString()}</span>
                </div>
                <div className="border-t border-white/5 pt-3 flex justify-between">
                  <span className="font-medium">Total Tax</span>
                  <span className="text-xl font-bold text-amber-400">${taxData.estimatedTax.toLocaleString()}</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Previous Years */}
          <Card className="bg-white/[0.02] border-white/5 rounded-xl">
            <CardContent className="p-6">
              <h2 className="font-semibold mb-4">Other Years</h2>
              <div className="space-y-3">
                {previousYears.map((year) => (
                  <button
                    key={year.year}
                    onClick={() => setSelectedYear(year.year)}
                    className="w-full p-3 bg-white/5 rounded-xl text-left hover:bg-white/10 transition-colors"
                  >
                    <div className="flex justify-between mb-1">
                      <span className="font-medium">{year.year}</span>
                      <span className="text-emerald-400">${year.income.toLocaleString()}</span>
                    </div>
                    <div className="text-xs text-zinc-500">
                      Expenses: ${year.expenses.toLocaleString()} • Tax: ${year.tax.toLocaleString()}
                    </div>
                  </button>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Disclaimer */}
      <Card className="mt-6 bg-blue-500/10 border-blue-500/20 rounded-xl">
        <CardContent className="p-4">
          <div className="flex items-start gap-3">
            <span className="text-xl">ℹ️</span>
            <div className="text-sm text-zinc-300">
              <strong>Disclaimer:</strong> These estimates are for planning purposes only and should not be considered tax advice.
              Please consult a qualified tax professional for accurate tax calculations and filing requirements.
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
